---
- name: Install Docker and Docker Compose, then run a Flask web application
  hosts: azure 
  become: true  

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Dockers official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Create directory for web application files
      file:
        path: /home/ubuntu/application
        state: directory

    - name: Clone the web application repository
      git:
        repo: https://github.com/HDGeeks/web_app.git
        dest: /home/ubuntu/application/web_app
        clone: yes
        update: yes

    - name: Change to the correct directory and run docker-compose up
      shell: |
        cd /home/ubuntu/application/web_app && docker-compose up -d
      args:
        chdir: /home/ubuntu/application/web_app
