---
- name: Append Docker Nginx location to existing configuration
  hosts: azure
  become: yes 
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Backup existing Nginx default configuration
      copy:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-available/default.bak
        remote_src: yes

    - name: Append the local web_app running in container in to the  Nginx location to the existing server block
      lineinfile:
        path: /etc/nginx/sites-available/default
        insertafter: 'server_name cgi-vm-demo3.germanywestcentral.cloudapp.azure.com;'
        line: |
          # Location for the Docker Nginx Container
          location /app {
              rewrite ^/app/(.*) /$1 break;
              proxy_pass http://localhost:5000;  # Forward requests to Docker container
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
        state: present
        create: yes

    - name: Validate Nginx configuration
      command: nginx -t
      register: nginx_test
      ignore_errors: yes  # Allow for errors to be captured

    - name: Show Nginx test result
      debug:
        var: nginx_test.stdout_lines

    - name: Reload Nginx if configuration is valid
      systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0  # Only reload if the command was successful

