# @format
---
- name: Install and Configure Nginx on Ubuntu
  hosts: azure
  become: true  # Enables sudo (privilege escalation) for all tasks

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Remove existing index.html if it exists
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy custom index.html to Nginx
      copy:
        src: files/index.html  # Separate index.html in the 'files' directory for best practices
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Make Nginx default configuration writable
      file:
        path: /etc/nginx/sites-enabled/default
        mode: '0666'  # Change permissions to make it writable

    - name: Ensure server_name is set in Nginx default configuration inside the server block
      blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} MANAGED BY ANSIBLE"
        insertafter: '^\\s*listen'  # Insert after the 'listen' directive inside the server block
        block: |
          server_name cgi-vm-demo.germanywestcentral.cloudapp.azure.com;
      notify: Restart Nginx



  handlers:
      - name: Restart Nginx
        service:
          name: nginx
          state: restarted
