# @format
---
- name: Install, Configure Nginx, and Prepare for SSL
  hosts: azure
  become: true  # Enables sudo (privilege escalation) for all tasks

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory

    - name: Remove existing index.html if it exists
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy custom index.html to Nginx
      copy:
        src: files/index.html  # Make sure this file exists in the 'files' directory
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure Nginx to serve custom index.html and handle Let's Encrypt challenge
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
            listen  80 default_server;
            server_name cgi-vm-demo1.germanywestcentral.cloudapp.azure.com;

            location / {
                root /var/www/html;  
                index index.html;    
            }

            location ~ /\.well-known/acme-challenge/ {
                allow all;
                root /var/www/letsencrypt;
                try_files $uri =404;
                break;
            }
          }
      notify: Restart Nginx

    - name: Ensure server_names_hash_bucket_size is set to 128 in Nginx config
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: 'server_names_hash_bucket_size'
        line: '    server_names_hash_bucket_size 128;'
        state: present
        insertafter: 'http {'
      notify:
        - Reload Nginx


    - name: Ensure /var/www/letsencrypt directory exists for Certbot challenges
      file:
        path: /var/www/letsencrypt
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Restart Nginx if configuration is valid
      service:
        name: nginx
        state: restarted
      when: nginx_test.rc == 0

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
