---
- name: Install NGINX and Deploy Custom Index Page
  hosts: azure
  become: true

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory

    - name: Remove existing index.html if it exists
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy custom index.html to Nginx
      copy:
        src:  files/index.html  
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Validate NGINX configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Restart NGINX if configuration is valid
      service:
        name: nginx
        state: restarted
      when: nginx_test.rc == 0
